src/Entity/Grade.php
<?php

namespace App\Entity;
use App\Repository\GradeRepository;
use DateTimeInterface;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: GradeRepository::class)]
//TODO: unique entity is not working
#[UniqueEntity(
    fields: ['test', 'grade'],
    message: 'Student already has a grade for this test',
    errorPath: 'student')]
class Grade
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $grade = null;

    #[ORM\ManyToOne(inversedBy: 'grades')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Test $test = null;

    #[ORM\ManyToOne(inversedBy: 'grades')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Student $student = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?DateTimeInterface $issue_datetime = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?DateTimeInterface $change_datetime = null;

    public function __toString(): string
    {
        return $this->getStudent() . ' - ' . $this->getGrade();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGrade(): ?float
    {
        return $this->grade;
    }

    public function setGrade(float $grade): static
    {
        $this->grade = $grade;

        return $this;
    }

    public function getTest(): ?Test
    {
        return $this->test;
    }

    public function setTest(?Test $test): static
    {
        $this->test = $test;

        return $this;
    }

    public function getStudent(): ?Student
    {
        return $this->student;
    }

    public function setStudent(?Student $student): static
    {
        $this->student = $student;

        return $this;
    }

    public function getIssueDatetime(): ?DateTimeInterface
    {
        return $this->issue_datetime;
    }

    public function setIssueDatetime(DateTimeInterface $issue_datetime): static
    {
        $this->issue_datetime = $issue_datetime;

        return $this;
    }

    public function getChangeDatetime(): ?DateTimeInterface
    {
        return $this->change_datetime;
    }

    public function setChangeDatetime(?DateTimeInterface $change_datetime): static
    {
        $this->change_datetime = $change_datetime;

        return $this;
    }
}

src/Entity/Teacher.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use App\Repository\TeacherRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

//TODO: Check why the serialization context is not working
#[ORM\Entity(repositoryClass: TeacherRepository::class)]
#[ApiResource(
    description: 'Teachers are users with a role of teacher',
    operations: [
        new Get(),
        new GetCollection(),
    ],
    normalizationContext: ['groups' => ['teacher:read'], 'jsonld_embed_context' => true],
    paginationEnabled: false,
)]
class Teacher
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['teacher:read'])]
    private ?int $id = null;

    #[ORM\OneToOne(mappedBy: 'teacher', cascade: ['persist', 'remove'])]
    private ?User $auth_user = null;

    #[ORM\OneToOne(mappedBy: 'home_teacher', cascade: ['persist', 'remove'])]
    private ?Course $course = null;


    #[ORM\OneToMany(mappedBy: 'teacher', targetEntity: Test::class, orphanRemoval: true)]
    private Collection $tests;

    #[ORM\OneToMany(mappedBy: 'teacher', targetEntity: CourseSubject::class)]
    private Collection $courseSubjects;

    public function __construct()
    {
        $this->tests = new ArrayCollection();
        $this->courseSubjects = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->getAuthUser()->getFullName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    #[Groups(['teacher:read', 'user:read'])]
    public function getAuthUser(): ?User
    {
        return $this->auth_user;
    }

    public function setAuthUser(?User $auth_user): static
    {
        // unset the owning side of the relation if necessary
        if ($auth_user === null && $this->auth_user !== null) {
            $this->auth_user->setTeacher(null);
        }

        // set the owning side of the relation if necessary
        if ($auth_user !== null && $auth_user->getTeacher() !== $this) {
            $auth_user->setTeacher($this);
        }

        $this->auth_user = $auth_user;

        return $this;
    }

    #[Groups(['teacher:read', 'course:read'])]
    public function getCourse(): ?Course
    {
        return $this->course;
    }

    public function setCourse(?Course $course): static
    {
        // unset the owning side of the relation if necessary
        if ($course === null && $this->course !== null) {
            $this->course->setHomeTeacher(null);
        }

        // set the owning side of the relation if necessary
        if ($course !== null && $course->getHomeTeacher() !== $this) {
            $course->setHomeTeacher($this);
        }

        $this->course = $course;

        return $this;
    }

    /**
     * @return Collection<int, Test>
     */
    public function getTests(): Collection
    {
        return $this->tests;
    }

    public function addTest(Test $test): static
    {
        if (!$this->tests->contains($test)) {
            $this->tests->add($test);
            $test->setTeacher($this);
        }

        return $this;
    }

    public function removeTest(Test $test): static
    {
        if ($this->tests->removeElement($test)) {
            // set the owning side to null (unless already changed)
            if ($test->getTeacher() === $this) {
                $test->setTeacher(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, CourseSubject>
     */
    public function getCourseSubjects(): Collection
    {
        return $this->courseSubjects;
    }

    /**
     * @return Collection<int, Subject>
     */
    public function getTeachingSubjects(): Collection
    {
        return new ArrayCollection(array_unique($this->courseSubjects
            ->map(
                fn(CourseSubject $courseSubject) => $courseSubject->getSubject()
            )
            ->toArray()
        ));
    }

    public function addCourseSubject(CourseSubject $courseSubject): static
    {
        if (!$this->courseSubjects->contains($courseSubject)) {
            $this->courseSubjects->add($courseSubject);
            $courseSubject->setTeacher($this);
        }

        return $this;
    }

    public function removeCourseSubject(CourseSubject $courseSubject): static
    {
        if ($this->courseSubjects->removeElement($courseSubject)) {
            // set the owning side to null (unless already changed)
            if ($courseSubject->getTeacher() === $this) {
                $courseSubject->setTeacher(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use App\Repository\UserRepository;
use DateTimeInterface;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use LogicException;
use Scheb\TwoFactorBundle\Model\Totp\TotpConfiguration;
use Scheb\TwoFactorBundle\Model\Totp\TotpConfigurationInterface;
use Scheb\TwoFactorBundle\Model\Totp\TwoFactorInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ApiResource(
    description: 'Users are the main entity of the system',
    operations: [new GetCollection(), new Get()],
    normalizationContext: ['groups' => ['user:read']],
)]
class User implements UserInterface, PasswordAuthenticatedUserInterface, TwoFactorInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;
    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $authCode;
    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $totpSecret;
    #[ORM\Column]
    #[Groups(['user:read'])]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    #[Groups(['user:read'])]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    #[Groups(['user:read'])]
    private ?string $last_name = null;

    #[ORM\OneToOne(inversedBy: 'auth_user', cascade: ['persist', 'remove'])]
    #[Groups(['user:read'])]
    private ?Teacher $teacher = null;

    #[ORM\OneToOne(inversedBy: 'auth_user', cascade: ['persist', 'remove'])]
    private ?Student $student = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['user:read'])]
    private ?string $address = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['user:read'])]
    private ?string $phone_number = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    #[Groups(['user:read'])]
    private ?DateTimeInterface $date_of_birth = null;

    public function __toString(): string
    {
        return $this->getFullName();
    }

    #[Groups(['user:read'])]
    public function getFullName(): string
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    #[Groups(['user:read'])]
    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function isEmailAuthEnabled(): bool
    {
        return true; // This can be a persisted field to switch email code authentication on/off
    }

    public function getEmailAuthRecipient(): string
    {
        return $this->email;
    }

    public function getEmailAuthCode(): string
    {
        if (null === $this->authCode) {
            throw new LogicException('The email authentication code was not set');
        }

        return $this->authCode;
    }

    public function setEmailAuthCode(string $authCode): void
    {
        $this->authCode = $authCode;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string)$this->email;
    }

    /**
     * @see UserInterface
     */
    #[Groups(['user:read'])]
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getTeacher(): ?Teacher
    {
        return $this->teacher;
    }

    public function setTeacher(?Teacher $teacher): static
    {
        $this->teacher = $teacher;

        return $this;
    }

    public function getStudent(): ?Student
    {
        return $this->student;
    }

    public function setStudent(?Student $student): static
    {
        $this->student = $student;

        return $this;
    }

    #[Groups(['user:read'])]
    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): static
    {
        $this->address = $address;

        return $this;
    }

    #[Groups(['user:read'])]
    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(?string $phone_number): static
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    #[Groups(['user:read'])]
    public function getDateOfBirth(): ?DateTimeInterface
    {
        return $this->date_of_birth;
    }

    public function setDateOfBirth(?DateTimeInterface $date_of_birth): static
    {
        $this->date_of_birth = $date_of_birth;

        return $this;
    }

    public function isTotpAuthenticationEnabled(): bool
    {
        return (bool)$this->totpSecret;
    }

    public function getTotpAuthenticationUsername(): string
    {
        return $this->getUserIdentifier();
    }

    public function getTotpAuthenticationConfiguration(): ?TotpConfigurationInterface
    {
        return new TotpConfiguration($this->totpSecret, TotpConfiguration::ALGORITHM_SHA1, 30, 6);
    }

    public function getAuthCode(): ?string
    {
        return $this->authCode;
    }

    public function setAuthCode(?string $authCode): void
    {
        $this->authCode = $authCode;
    }

    public function setTotpSecret(?string $totpSecret): void
    {
        $this->totpSecret = $totpSecret;
    }


}

src/Controller/TeacherController.php
<?php

namespace App\Controller;

use App\Service\TeacherService;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TeacherController extends BaseController
{
    private TeacherService $teacherService;

    /**
     * @param TeacherService $teacherService
     */
    public function __construct(TeacherService $teacherService)
    {
        $this->teacherService = $teacherService;
    }

    #[Route('/teacher', name: 'app_teacher')]
    public function index(): Response
    {
        return $this->render('teacher/index.html.twig', [
            'controller_name' => 'TeacherController',
        ]);
    }

    #[Route('/teacher/grade', name: 'app_teacher_grade')]
    public function grade(): Response
    {
        $teacherId = $this->getUser()->getTeacher()->getId();
        $subjectsByCourse = $this->teacherService->getTeachingSubjectsGroupedByCourseForTeacherId($teacherId);
        dump($subjectsByCourse);
        return $this->render('teacher/grade/index.html.twig', [
            'controller_name' => 'TeacherController',
            'subjectsByCourse' => $subjectsByCourse
        ]);
    }

    #[Route('/teacher/grade/{courseSubjectId<\d+>}', name: 'app_teacher_grade_course_subject')]
    public function grading($courseSubjectId = null): Response
    {
        $gradesOnTest = $this->teacherService->getStudentsGradesForCourseSubject($courseSubjectId);
        $students = $this->teacherService->getStudentsInCourseSubject($courseSubjectId);
        return $this->render('teacher/grade/grading.html.twig', [
            'gradesOnTest' => $gradesOnTest,
            'studentCount' => $students,
            'courseSubjectId' => $courseSubjectId
        ]);
    }

    #[Route('/teacher/test/{courseSubjectId<\d+>}', name: 'app_teacher_add_test')]
    public function addTest(int $courseSubjectId): Response
    {
        return $this->render('teacher/test/add_test.html.twig', [
            'courseSubjectId' => $courseSubjectId
        ]);
    }

    #[Route('/teacher/test/edit/{testId<\d+>}', name: 'app_teacher_edit_test')]
    public function editTest(int $testId): Response
    {
        $test = $this->teacherService->getTestById($testId);

        return $this->render('teacher/test/edit_test.html.twig', [
            'test' => $test
        ]);
    }

    #[Route('/teacher/grade/{courseSubjectId<\d+>}/{testId<\d+>}', name: 'app_teacher_grade_test')]
    public function addGrades(int $courseSubjectId, int $testId): Response
    {

        $studentEntities = $this->teacherService->getStudentsInCourseSubject($courseSubjectId);
        $studentsIds = [];
        foreach ($studentEntities as $student) {
            $studentsIds[] = $student->getId();
        }
        return $this->render('teacher/grade/add_grades.html.twig', [
            'test_id' => $testId,
            'studentsIds' => $studentsIds,
            'courseSubjectId' => $courseSubjectId
        ]);
    }

    /**
     * @param int $gradeId
     * @return Response
     */
    #[Route('/teacher/grade/edit/{gradeId<\d+>}', name: 'app_teacher_grade_edit')]
    public function editGrade(int $gradeId): Response
    {
        $grade = $this->teacherService->getGradeById($gradeId);

        return $this->render('teacher/grade/edit_grade.html.twig', [
            'controller_name' => 'TeacherController',
            'grade' => $grade
        ]);

    }
}

templates/teacher/grade/add_grades.html.twig
{% extends 'base.html.twig' %}
{% block title %} Dodawanie ocen {% endblock %}
{% block body %}
    {% block addGrades %}
        {{ component('AddGradesToTestForm', {
            'testId': test_id,
            'studentsIds': studentsIds,
        }) }}

    {% endblock %}
{% endblock %}

templates/teacher/grade/edit_grade.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <turbo-frame id="grading">
        {{ component('EditGradeForm',{
            'grade': grade,
        }) }}
    </turbo-frame>
{% endblock %}

templates/teacher/grade/grading.html.twig
{% block subjectGrades %}
    <turbo-frame id="grading">

        <a href="{{ path('app_teacher_add_test', {'courseSubjectId' : courseSubjectId}) }}"
        >
            <button type="button"
                    class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center mr-3 lg:mr-0 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                Add test
            </button>
        </a>


        <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
            {% for test in gradesOnTest %}
                <a class="dark:text-white">{{ test.name }} ({{ test.grades|length }}/{{ studentCount|length }})
                    ({{ test.weight }})</a>
                <a href="{{ path('app_teacher_edit_test', {'testId' : test.id}) }}">
                    <button type="button"
                            class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center mr-3 lg:mr-0 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                        Edit Test
                    </button>
                </a>
                {% if test.grades|length < studentCount|length %}
                <a href="{{ path('app_teacher_grade_test', {'courseSubjectId' : courseSubjectId, 'testId' : test.id}) }}"
                   target="_top">
                    <button type="button"
                            class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center mr-3 lg:mr-0 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                        Add Grades
                    </button>
                </a>
                {% endif %}
                <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr>
                        <th scope="col" class="px-6 py-3">
                            Name and Surname
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Grade
                        </th>
                        <th scope="col" class="px-6 py-3 text-right">
                            Actions
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for grade in test.grades %}
                        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                            <th scope="row"
                                class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                {{ grade.student.authUser.firstName }} {{ grade.student.authUser.lastName }}
                            </th>
                            <td class="px-6 py-4">
                                {{ grade.grade }}
                            </td>
                            <td class="px-6 py-4 text-right">
                                <a href="{{ path('app_teacher_grade_edit', {'gradeId' : grade.id}) }}"
                                   class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Edit</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endfor %}
        </div>
    </turbo-frame>
{% endblock %}

templates/teacher/grade/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="flex h-full flex-row">
        <aside id="default-sidebar" class="z-40 w-64 h-full transition-transform -translate-x-full sm:translate-x-0 "
               aria-label="Sidenav">
            <div class="overflow-y-auto py-5 px-3 h-full bg-white border-r border-gray-200 dark:bg-gray-800 dark:border-gray-700 rounded-r-lg">
                <ul class="space-y-2">
                    <li id="accordion-collapse" data-accordion="open">
                        {% for courseId, subjects in subjectsByCourse %}
                            <h2 id="accordion-collapse-heading-{{ loop.index }}">
                                <button type="button"
                                        class="flex items-center justify-between w-full p-5 font-medium text-left text-gray-500 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-800 dark:border-gray-700 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800"
                                        data-accordion-target="#accordion-collapse-body-{{ loop.index }}"
                                        aria-expanded="true"
                                        aria-controls="accordion-collapse-body-{{ loop.index }}"
                                >
                                    <span>{{ subjects.courseName }}</span>
                                    <svg data-accordion-icon class="w-3 h-3 rotate-180 shrink-0" aria-hidden="true"
                                         xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                              stroke-width="2" d="M9 5 5 1 1 5"></path>
                                    </svg>
                                </button>
                            </h2>
                            <div id="accordion-collapse-body-{{ loop.index }}" class="hidden"
                                 aria-labelledby="accordion-collapse-heading-1">
                                <ul class=" py-2 space-y-2">
                                    {% for key , subject in subjects.subjects %}
                                        <li>
                                            <a href="{{ path('app_teacher_grade_course_subject', {'courseSubjectId': key}) }}"
                                               data-turbo-action="replace"
                                               data-turbo-frame="grading"
                                               class="flex items-center p-2 pl-11 w-full text-base font-normal text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700">{{ subject.name }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endfor %}
                    </li>
                </ul>
            </div>
        </aside>
        {% block subjectGrades %}
            <turbo-frame id="grading">

            </turbo-frame>
        {% endblock %}
    </div>
{% endblock %}