src/Entity/User.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use App\Repository\UserRepository;
use DateTimeInterface;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use LogicException;
use Scheb\TwoFactorBundle\Model\Totp\TotpConfiguration;
use Scheb\TwoFactorBundle\Model\Totp\TotpConfigurationInterface;
use Scheb\TwoFactorBundle\Model\Totp\TwoFactorInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ApiResource(
    description: 'Users are the main entity of the system',
    operations: [new GetCollection(), new Get()],
    normalizationContext: ['groups' => ['user:read']],
)]
class User implements UserInterface, PasswordAuthenticatedUserInterface, TwoFactorInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;
    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $authCode;
    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $totpSecret;
    #[ORM\Column]
    #[Groups(['user:read'])]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    #[Groups(['user:read'])]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    #[Groups(['user:read'])]
    private ?string $last_name = null;

    #[ORM\OneToOne(inversedBy: 'auth_user', cascade: ['persist', 'remove'])]
    #[Groups(['user:read'])]
    private ?Teacher $teacher = null;

    #[ORM\OneToOne(inversedBy: 'auth_user', cascade: ['persist', 'remove'])]
    private ?Student $student = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['user:read'])]
    private ?string $address = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['user:read'])]
    private ?string $phone_number = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    #[Groups(['user:read'])]
    private ?DateTimeInterface $date_of_birth = null;

    public function __toString(): string
    {
        return $this->getFullName();
    }

    #[Groups(['user:read'])]
    public function getFullName(): string
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    #[Groups(['user:read'])]
    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function isEmailAuthEnabled(): bool
    {
        return true; // This can be a persisted field to switch email code authentication on/off
    }

    public function getEmailAuthRecipient(): string
    {
        return $this->email;
    }

    public function getEmailAuthCode(): string
    {
        if (null === $this->authCode) {
            throw new LogicException('The email authentication code was not set');
        }

        return $this->authCode;
    }

    public function setEmailAuthCode(string $authCode): void
    {
        $this->authCode = $authCode;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string)$this->email;
    }

    /**
     * @see UserInterface
     */
    #[Groups(['user:read'])]
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getTeacher(): ?Teacher
    {
        return $this->teacher;
    }

    public function setTeacher(?Teacher $teacher): static
    {
        $this->teacher = $teacher;

        return $this;
    }

    public function getStudent(): ?Student
    {
        return $this->student;
    }

    public function setStudent(?Student $student): static
    {
        $this->student = $student;

        return $this;
    }

    #[Groups(['user:read'])]
    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): static
    {
        $this->address = $address;

        return $this;
    }

    #[Groups(['user:read'])]
    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(?string $phone_number): static
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    #[Groups(['user:read'])]
    public function getDateOfBirth(): ?DateTimeInterface
    {
        return $this->date_of_birth;
    }

    public function setDateOfBirth(?DateTimeInterface $date_of_birth): static
    {
        $this->date_of_birth = $date_of_birth;

        return $this;
    }

    public function isTotpAuthenticationEnabled(): bool
    {
        return (bool)$this->totpSecret;
    }

    public function getTotpAuthenticationUsername(): string
    {
        return $this->getUserIdentifier();
    }

    public function getTotpAuthenticationConfiguration(): ?TotpConfigurationInterface
    {
        return new TotpConfiguration($this->totpSecret, TotpConfiguration::ALGORITHM_SHA1, 30, 6);
    }

    public function getAuthCode(): ?string
    {
        return $this->authCode;
    }

    public function setAuthCode(?string $authCode): void
    {
        $this->authCode = $authCode;
    }

    public function setTotpSecret(?string $totpSecret): void
    {
        $this->totpSecret = $totpSecret;
    }


}

templates/components/AddGradesToTestForm.html.twig
<div
        {{ attributes }}
>

    {{ form_start(form, {
        attr: {
            'novalidate': true,
            'data-action': 'live#action',
            'data-action-name': 'prevent|saveGrades',
        }
    }) }}
    <table class="">
        <thead>
        <tr>
            <td>Student</td>
            <td>Grade</td>
        </tr>
        </thead>
        <tbody>
        {% for key, gradeItem in form.grades %}
            <tr>
                <td>
                    {{ form_row(gradeItem.student, {
                        label: false,
                    }) }}
                </td>

                <td>
                    {{ form_row(gradeItem.grade, {
                        label: false,
                    }) }}
                </td>
                <td>
                    {{ form_row(
                        gradeItem.vars.button_delete,
                        { label: 'X',
                            attr:
                            { class: '' }
                        }) }}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {{ form_widget(
        form.grades.vars.button_add,
        { label: '+ Add Item', attr:
            { class: 'btn btn-outline-primary' }
        }) }}
    <button type="submit" class="text-white" formnovalidate>Dodaj ocenę</button>
    {{ form_end(form) }}
</div>

templates/components/AddTestForm.html.twig
<div
        {{ attributes }}
>

    {{ form_start(form, {
        attr: {
            'novalidate': true,
            'data-action': 'live#action',
            'data-action-name': 'prevent|saveTest',
        }
    }) }}
    {{ form_end(form) }}
</div>

templates/components/EditGradeForm.html.twig
<div
        {{ attributes }}
>

    {{ form_start(form, {
        attr: {
            'novalidate': true,
            'data-action': 'live#action',
            'data-action-name': 'prevent|saveChanges',
        }
    }) }}
    {{ form_row(form.grade) }}
    {{ form_end(form) }}
</div>

templates/components/EditTestForm.html.twig
<div
        {{ attributes }}
>

    {{ form_start(form, {
        attr: {
            'novalidate': true,
            'data-action': 'live#action',
            'data-action-name': 'prevent|saveChanges',
        }
    }) }}
    {{ form_row(form.name) }}
    {{ form_row(form.datetime) }}
    {{ form_row(form.weight) }}
    {{ form_row(form.status) }}
    {{ form_widget(form.save) }}


    <button data-modal-target="popup-modal" data-modal-toggle="popup-modal"
            class="text-white bg-red-600 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg text-sm inline-flex items-center px-5 py-2.5 text-center mr-2"
            type="button">
        Delete Test
    </button>

    <div id="popup-modal" tabindex="-1"
         class="fixed top-0 left-0 right-0 z-50 hidden p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
        <div class="relative w-full max-w-md max-h-full">
            <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                <button type="button"
                        class="absolute top-3 right-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ml-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white"
                        data-modal-hide="popup-modal">
                    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                         viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"></path>
                    </svg>
                    <span class="sr-only">Close modal</span>
                </button>
                <div class="p-6 text-center">
                    <svg class="mx-auto mb-4 text-gray-400 w-12 h-12 dark:text-gray-200" aria-hidden="true"
                         xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="M10 11V6m0 8h.01M19 10a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"></path>
                    </svg>
                    <h3 class="mb-5 text-lg font-normal text-gray-500 dark:text-gray-400">Are you sure you want to
                        delete this test?</h3>
                    <button data-action="live#action"
                            data-action-name="deleteTest" data-modal-hide="popup-modal" type="button"
                            class="text-white bg-red-600 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg text-sm inline-flex items-center px-5 py-2.5 text-center mr-2">
                        Yes, I'm sure
                    </button>
                    <button data-modal-hide="popup-modal" type="button"
                            class="text-gray-500 bg-white hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-200 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 hover:text-gray-900 focus:z-10 dark:bg-gray-700 dark:text-gray-300 dark:border-gray-500 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-600">
                        No, cancel
                    </button>
                </div>
            </div>
        </div>
    </div>

    {{ form_end(form) }}
</div>

templates/components/RegistrationForm.html.twig
<div
        {{ attributes }}
>
    {{ form_start(form, {
        attr: {
            'novalidate': true,
            'data-action': 'live#action',
            'data-action-name': 'prevent|saveRegistration',
        }
    }) }}
    {{ form_row(form.role) }}
    {{ form_row(form.email) }}
    {{ form_row(form.first_name) }}
    {{ form_row(form.last_name) }}
    {{ form_row(form.phone_number) }}
    {{ form_row(form.address) }}
    {{ form_row(form.dateOfBirth) }}
    {{ form_row(form.password) }}
    {{ form_row(form.terms) }}


    {{ form_rest(form) }}
    <button type="submit"
            class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        Submit
    </button>
    {{ form_end(form) }}
</div>